#!/usr/bin/env bash

export SERVICE="Crowd"
export WAIT_TIME=30

do_health() {
  STATUS=0
  check_traefik ${SERVICE_DOMAIN} "HTTP/1.1 302 Found" || STATUS=$?
  return $STATUS
}

. ../../meta/bee.sh "${@}"
