#!/usr/bin/env bash

export SERVICE="Rundeck"
export WAIT_TIME=90

do_health() {
  STATUS=0
  check_traefik ${SERVICE_DOMAIN} "HTTP/1.1 302 Found" || STATUS=$?
  return $STATUS
}

do_upgrade() {
  docker-compose pull
  docker-compose down
}

. ../../meta/bee.sh "${@}"
