#!/usr/bin/env bash

export SERVICE="GitLab"
export WAIT_TIME=45

do_health() {
  STATUS=0
  check_traefik ${SERVICE_DOMAIN} "HTTP/1.1 302 Found" || STATUS=$?
  return $STATUS
}

sub_upgrade() {
  sub_backup
  sub_up
}

. ../../meta/bee.sh "${@}"
