#!/usr/bin/env bash

export SERVICE="Redash"
export WAIT_TIME=90

sub_init() {
  echo "Initializing Redash"
  docker-compose run --rm server create_db
}

do_health() {
  STATUS=0
  check_traefik ${SERVICE_DOMAIN} "HTTP/1.1 302 Found" || STATUS=$?
  return $STATUS
}

. ../../meta/bee.sh "${@}"
