#!/usr/bin/env bash

export SERVICE="Minio"
export WAIT_TIME=5

do_health() {
  STATUS=0
  check_curl ${SERVICE_DOMAIN}/minio/ "HTTP/1.1 200 OK" || STATUS=$?
  return $STATUS
}

. ../../meta/bee.sh "${@}"
