#!/usr/bin/env bash

export SERVICE="Dependency-Track"
export WAIT_TIME=5

do_health() {
  STATUS=0
  check_traefik ${SERVICE_DOMAIN} "HTTP/1.1 200 OK" || STATUS=$?
  return $STATUS
}

. ../../meta/bee.sh "${@}"
