#!/usr/bin/env bash

export SERVICE="Sentry"
export WAIT_TIME=20

sub_init() {
  loadenv $1
  docker-compose up -d redis postgres
  wait 20
  docker-compose run --rm server upgrade
}

sub_upgrade() {
  sub_init $1
}

do_health() {
  STATUS=0
  check_traefik ${SERVICE_DOMAIN} "HTTP/1.1 302 Found" || STATUS=$?
  return $STATUS
}

. ../../meta/bee.sh "${@}"
